### ISSUE TITLE
Does not work corretly when code.exe window is not maximized

### ISSUE THREAD

**Issue by xmedeko** [DanielBoxer/VSCroll#2]
Make VS Code window not maximized, rather smaller. 
1. I have tried the script, but the symbol mode was to much on the right - out of the window.
2. So, I have commented out the first `CoordMode`, line 40. Then the symbol was on the right place. But when I have scrolled to the very end of a file, released middle button, press it again - symbol is on the right place, but I cannot scroll up.

Note: https://github.com/qooqu/vs-code-mbutton-scroll-ahk/blob/main/script.ahk is working well.

**Comment by danielboxer** [comment]
It should be fixed now. Can you try it out and let me know if it's working for you?

**Comment by xmedeko** [comment]
Perfect, works like a charm. Thanks for a quick fix.

Note: I have added `#SingleInstance Force` to get rid of a dialog when changing the code and reloading the script.
